title: GenericStuff
description: GenericStuff is a collection of Luau ModuleScripts used for doing various stuff
show_downloads: true
remote_theme: MrSpokes/cayman
color:
  header: "#fff"
  gradient_left: "#010332"
  gradient_right: "#530005"
  android_theme: "#fff"
  link: "#1e6bb8"
  section_title: "#fff"
