title: GenericStuff
description: GenericStuff is a group of Luau ModuleScripts for doing all kinds of stuff.
show_downloads: true
darkmode: true
remote_theme: tuur29/pages-themes-cayman
color:
  header: "#fff"
  gradient_left: "#010332"
  gradient_right: "#530005"
syntax_theme: https://stylishthemes.github.io/Syntax-Themes/pygments/css-github/pygments-monokai.css
buttons:
  zip_url: https://github.com/MrSpokes/GenericStuff
  zip_title: View Documentation
  zip_hide: false
  tar_hide: true
  github_hide: true
