theme: jekyll-theme-cayman
darkmode: true
hide_first_title: false
colors:
    gradient_left: "#010332"
    gradient_right: "#530005"
    header: "#fff"
    android_theme: "#000"
    link: "#1e6bb8"
    section_title: "#010332"
